language: c
script: travis_wait asdf plugin-test erlang https://github.com/asdf-vm/asdf-erlang.git
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
os:
  - linux
  - osx
install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install -y xsltproc fop; fi
